name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}   # diana1927
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}             # mi-app-test
      IMAGE_TAG: ${{ vars.IMAGE_TAG }}               # latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # o ${{ secrets.DOCKER_PASSWORD }} si lo llamaste así

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate variables
        run: |
          set -e
          echo "DOCKER_USERNAME=${DOCKER_USERNAME}"
          echo "IMAGE_NAME=${IMAGE_NAME}"
          echo "IMAGE_TAG=${IMAGE_TAG}"
          [ -n "${DOCKER_USERNAME}" ] || { echo "❌ DOCKER_USERNAME vacío"; exit 1; }
          [ -n "${IMAGE_NAME}" ]      || { echo "❌ IMAGE_NAME vacío"; exit 1; }
          [ -n "${IMAGE_TAG}" ]       || { echo "❌ IMAGE_TAG vacío"; exit 1; }
          echo "${DOCKER_USERNAME}" | grep -Eq '^[a-z0-9]+([._-][a-z0-9]+)*$' || { echo "❌ DOCKER_USERNAME inválido"; exit 1; }
          echo "${IMAGE_NAME}"      | grep -Eq '^[a-z0-9]+([._-][a-z0-9]+)*$' || { echo "❌ IMAGE_NAME inválido"; exit 1; }

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
